## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
    # - APP-FUNC-TEST
    #  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/builds/openebs/e2e-eks/script/utils"

## Setup the kubernetes cluster

eks-cluster:
  image: atulabhi/kops:v10
  stage: CLUSTER-SETUP 
  script:
    - chmod 775 ./script/eks 
    - ./script/eks
  artifacts:
    paths:
      - .kube/

## Setup OpenEBS control plane

openebs-eks-deploy:
  image: atulabhi/kops:v10
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - eks-cluster
  script: 
   - chmod 775 ./script/provider/infra-setup
   - ./script/provider/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

## Define a job template for app deployers

.app_deploy_template:
  image: atulabhi/kops:v10
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-eks-deploy
  artifacts:
    paths: 
     - .kube-openebs/

## Define the app deployer jobs

## PERCONA-JIVA
percona-jiva-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-jiva

percona-jiva-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/jiva/percona-app-workload-jiva


# PERCONA-CSTOR
percona-cstor-run/load/check 0:2:
  extends: .app_deploy_template
  script: 
   - ./script/apps/percona/deployer/percona-app-deploy-cstor

percona-cstor-run/load/check 1:2:
  extends: .app_deploy_template
  before_script: 
   - sleep 180
  script: 
   - ./script/apps/percona/workload/cstor/percona-app-workload-cstor

cleanup-eks:
  when: always
  image: atulabhi/kops:v10
  dependencies:
    - eks-cluster
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 755 ./script/eks-cleanup
    - ./script/eks-cleanup
