stages:
  - cluster-setup
  - infra-setup
  - stateful-apps-deploy
  - chaos-test
  - cleanup
eks-cluster:
  image: atulabhi/kops:v10
  stage: cluster-setup
  script: 
    - chmod 775 ./script/eks
    - ./script/eks
  artifacts:
    when: always
    paths:
      - .kube/

openebs_eks_deploy:
  image: atulabhi/kops:v10
  stage: infra-setup
  dependencies:
    - eks-cluster
  script:
    - echo "Setting up infrastructure"
    - chmod 775 ./script/infra-setup
    - ./script/infra-setup
  artifacts:
    paths:
      - .kube-openebs/

percona-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/percona-app-deploy
    - ./script/percona-app-deploy
  dependencies:
    - openebs_eks_deploy

cassandra-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/cassandra-app-deploy
    - ./script/cassandra-app-deploy
  dependencies:
    - openebs_eks_deploy

mongo-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/mongo-app-deploy
    - ./script/mongo-app-deploy
  dependencies:
    - openebs_eks_deploy

jenkins-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/jenkins-app-deploy
    - ./script/jenkins-app-deploy
  dependencies:
    - openebs_eks_deploy

postgres-jiva:
  stage: stateful-apps-deploy
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/postgres-app-deploy
    - ./script/postgres-app-deploy
  dependencies:
    - openebs_eks_deploy
     
Litmus-Chaos:
  stage: chaos-test
  image: atulabhi/kops:v10
  script:
    - chmod 775 ./script/app-chaos
    - ./script/app-chaos
  dependencies:
    - openebs_eks_deploy

cleanup-eks:
  image: atulabhi/kops:v10
  dependencies:
    - eks-cluster
  stage: cleanup
  script: 
    - chmod 775 ./script/eks-cleanup
    - ./script/eks-cleanup
  when: always
